import {faker} from '@faker-js/faker';
import {CONSTANTS} from './../../../../helper'

const shiftName = 'Test shift (autogenerated) - ';

const recurrenceRule = {
    frequencyType: 'None',
    byDay: [
        'Sunday'
    ],
    interval: 0,
    count: 0,
    endTime: CONSTANTS.timestamp
};

const resources = {
    resourceId: 0,
    resourceType: CONSTANTS.resourceTypes[1]

};

const timeIntervals = {
    startTime: CONSTANTS.startTime,
    endTime: CONSTANTS.endTime
};

const groupResources = {
    internId: 0,
    pairedInternId: 0
};

const validShiftPayload = {
    name: `${shiftName}${faker.datatype.uuid()}`,
    availableForEhr: true,
    availableForPatientPortal: true,
    locationId: CONSTANTS.locationId,
    practitionerId: CONSTANTS.practitionerId,
    group: {
        supervisorId: 0,
        resources: [{...groupResources}]
    },
    startDate: CONSTANTS.timestamp,
    recurrenceRule: {...recurrenceRule},
    resources: [{...resources}],
    timeIntervals: [{...timeIntervals}]
};

const updateShiftPayload = {
    id: 0,
    ...validShiftPayload,
    availableForPatientPortal: false
};

const validShiftMakeupPayload = {
    shiftId: 0,
    ...validShiftPayload
};

export {
    validShiftPayload,
    updateShiftPayload,
    validShiftMakeupPayload
}