import {faker} from '@faker-js/faker';
import {CONSTANTS} from './../../../../helper'

const roomReservationTitle = 'Test rooms-reservations (autogenerated) - ';
const recurrenceRule = {
    frequencyType: 'Weekly',
    byDay: [
        'Sunday'
    ],
    interval: 1,
    endTime: CONSTANTS.timestampPlusOneHour
};

const validRoomsReservationsPayload = {
    id: 9999,
    title: `${roomReservationTitle}${faker.datatype.uuid()}`,
    description: `${faker.random.words(3)}`,
    locationId: CONSTANTS.locationId,
    rooms: [1],
    startTime: CONSTANTS.timestamp,
    endTime: CONSTANTS.timestampPlusOneHour,
    isAllDayEvent: false,
    rRule: {...recurrenceRule}
}

const validUpdateRoomsReservationsPayload = {
    ...validRoomsReservationsPayload,
    description: `${faker.random.words(5)}`
}

export {
    validRoomsReservationsPayload,
    validUpdateRoomsReservationsPayload
}