import {faker} from '@faker-js/faker';
import {CONSTANTS} from './../../../../helper'

const timeoffTitle = 'Test timeoff (autogenerated) - ';
const recurrenceRule = {
    frequencyType: 'Weekly',
    byDay: [
        'Sunday'
    ],
    interval: 1,
    endTime: CONSTANTS.timestampPlusOneDay
};

const validTimeoffsPayload = {
    title: `${timeoffTitle}${faker.datatype.uuid()}`,
    description: `${faker.random.words(3)}`,
    location: CONSTANTS.locationId,
    practitioners: [CONSTANTS.objectId],
    startTime: CONSTANTS.timestamp,
    endTime: CONSTANTS.timestampPlusOneDay,
    isAllDayEvent: false,
    rRule: {...recurrenceRule}
}

const validUpdateTimeoffsPayload = {
    ...validTimeoffsPayload,
    description: `${faker.random.words(5)}`
}

export {
    validTimeoffsPayload,
    validUpdateTimeoffsPayload
}