name: Run Cypress tests

on:
  workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/tests

      - name: "upload Cypress videos"
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore